import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body>
        <header className="bg-black p-4 sticky top-0">
          <Link href="/">
            <h1 className="text-3xl text-white font-bold">My Movies</h1>
          </Link>
        </header>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
